### ISSUE TITLE
Stream name /hls/anyname is not accepted

### ISSUE THREAD

**Issue by davidoster** [datarhei/restreamer-edge#2]
When I try to have something like this:
rtmp://xxx.yyy/hls/mystream?token=zzzz on my streaming software (OBS) the rtmp server module is denying the connection and OBS says: 
[http://prntscr.com/cyztll](http://prntscr.com/cyztll)
Any insights?

**Comment by jstabenow** [comment]
This should work:
![obs](https://cloud.githubusercontent.com/assets/7462030/19963547/27969fb0-a1bd-11e6-94bd-2abec469f2df.png)

**Comment by davidoster** [comment]
Silly me! Didn't think of this! I'll try it right away!
Thank you.
