### ISSUE TITLE
Custom transcoding profiles

### ISSUE THREAD

**Issue by MisterX2000** [datarhei/restreamer-edge#3]
It would be awesome if you could specify custom ffmpeg arguments, that are used for the transcoding process.
For example, so I can have a 720p version with 5.1 audio support, that doesn't sound rubbish.

**Comment by jstabenow** [comment]
I have never tested multichannel audio, but you can modify the profiles [here](https://github.com/datarhei/restreamer-edge/tree/master/templates/ffmpeg_profiles), mount them (-v $PWD/ffmpeg_profiles:/templates/ffmpeg_profiles) or build a new Docker image with your changes.
Good luck!

**Comment by MisterX2000** [comment]
I've mounted my customized profiles and it works, thanks! 😄

**Comment by jstabenow** [comment]
nice to hear and really cool! 😄  best thanks for the feedback
