### ISSUE TITLE
Transcoding doesn't work in v0.1.0

### ISSUE THREAD

**Issue by MisterX2000** [datarhei/restreamer-edge#4]
I just updated to v0.1.0, but now transcoding doesn't work anymore. I've set:
```
-e "RTMP_SRV_APP_HLS_TRANSCODING=true"
-e "RTMP_SRV_APP_HLS_TRANSCODING_PROFILES=480p,native"
```
and it only shows `1: 'native', 0: '480p',` in the Browser.

When I remove these 2 Environment variables it works fine.

**Comment by jstabenow** [comment]
orrr ... yes sorry. looks like an problem with sed. I am working on it

**Comment by jstabenow** [comment]
Okay should be fixed. Can you test this image? datarhei/restreamer-edge:master

**Comment by MisterX2000** [comment]
Yep works.
Thanks for the fast response.

**Comment by jstabenow** [comment]
perfect and no problem
