### ISSUE TITLE
documentation: best configuration hardware?

### ISSUE THREAD

**Issue by matigumma** [datarhei/restreamer-edge#6]
Hello, i want to know the hardware configuration for optimal performance
or the basis of hardware requeriments ;
cpu , 
multitread cpu, 
higger cpu freq 
or + cache, 
ram performance speed or amount.
disk i/o speed 

in my last use of this i was looking in htop high levels of cpu instead of ram.
can give me an approach of this?

**Comment by jstabenow** [comment]
Hey!

It would be helpful if you could say something about the requirements (number of users, number of streams, stream bandwidth, transcoding, lenght of playlist, type of livestream, ...).

Just try to describe your project and I try to help you.
